INSERT INTO Equipo (codigo_pais, nombre_pais)
VALUES
('ARG', 'Argentina'),
('AUS', 'Australia'),
('BEL', 'Bélgica'),
('BRA', 'Brasil'),
('CAN', 'Canadá'),
('CRO', 'Croacia'),
('ECU', 'Ecuador'),
('ENG', 'Inglaterra'),
('FRA', 'Francia'),
('GHA', 'Ghana'),
('IRN', 'Irán'),
('JPN', 'Japón'),
('KOR', 'Corea del Sur'),
('MAR', 'Marruecos'),
('MEX', 'México'),
('NED', 'Países Bajos'),
('POL', 'Polonia'),
('POR', 'Portugal'),
('QAT', 'Catar'),
('RSA', 'Arabia Saudita'),
('SEN', 'Senegal'),
('SER', 'Serbia'),
('ESP', 'España'),
('SUI', 'Suiza'),
('TUN', 'Túnez'),
('USA', 'Estados Unidos');
